load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

EM_TOOLCHAIN = """
package(default_visibility = ['//visibility:public'])

filegroup(
  name = "all",
  srcs = glob(["**/*"]),
)
"""

EM_CLANG = """
package(default_visibility = ['//visibility:public'])

filegroup(
  name = "all",
  srcs = glob(["**/*"]),
)
"""

http_archive(
  name = 'emscripten_toolchain',
  url = 'https://github.com/kripken/emscripten/archive/1.38.31.tar.gz',
  build_file_content = EM_TOOLCHAIN,
  strip_prefix = "emscripten-1.38.31",
)

http_archive(
  name = 'emscripten_clang',
  url = 'https://s3.amazonaws.com/mozilla-games/emscripten/packages/llvm/tag/linux_64bit/emscripten-llvm-e1.38.31.tar.gz',
  build_file_content = EM_CLANG,
  strip_prefix = "emscripten-llvm-e1.38.31",
)
